import type { Metadata } from "next";
import "./globals.css";

// 使用本地系统字体，避免网络字体下载问题
const fontSans = "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
        style={{ fontFamily: fontSans }}
      >
        {children}
      </body>
    </html>
  );
}
